### ISSUE TITLE
All the files are private

### ISSUE THREAD

**Issue by micheleorsi** [jiaqi/cym2#3]
Hi tried this plugin, but all the file are uploaded as "private" and not "public".
Is there a way to specify I want all the files and directories public? (I am uploading a site for documentation purpose)

**Comment by jiaqi** [comment]
The bucket needs to be open to public first. Have you set bucket policy? My bucket policy is

{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Sid": "PublicReadGetObject",
			"Effect": "Allow",
			"Principal": {
				"AWS": "*"
			},
			"Action": "s3:GetObject",
			"Resource": "arn:aws:s3:::mybucket/*"
		}
	]
}

**Comment by micheleorsi** [comment]
You're right! 
Sorry but I didn't know very well the bucket policy. Now it's more clear and it works!

Thanks
